### ISSUE TITLE
Using brfs transform?

### ISSUE THREAD

**Issue by niksy** [hughsk/ify-loader#4]
How would you use this loader with `brfs` transform?

My input is:

```js
var fs = require('fs');
var a = fs.readFileSync('./foo', 'utf8');
```

The output is:

```js
var fs = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"fs\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
var a = fs.readFileSync('./foo', 'utf8');
```

**Comment by mattdesl** [comment]
Check out this part of the readme, which explains how to set up `ify-loader` for local files:

https://github.com/hughsk/ify-loader#using-transforms-in-your-project
