### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by bpiwowar** [hughsk/ify-loader#6]
Thanks for your webpack module!

I had a trouble with the `regl` that was using a relative path
```js
  "browserify": {
    "transform": "browserify/transform"
  },
```

The error message I got was
```
ERROR in ./~/regl/dist/regl.js
Module build failed: Error: Cannot find module 'browserify/transform' from '[...]/node_modules/regl/dist'
```

As a quickfix I changed the path to `../browserify/transform` but this is not satisfying - I am unsure how to modify your code to get this work seamlessly.

**Comment by hughsk** [comment]
Aha! Good catch, thanks for the bug report.

Essentially, transforms in `package.json` were being resolved relative to the current file rather than the `package.json` file. Fix incoming 🎉
